# Generated by Django 5.0.1 on 2024-03-05 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('subscription_name', models.CharField(help_text='product name + validity + publisher id')),
                ('category', models.CharField(blank=True, null=True)),
                ('resource_type', models.CharField(choices=[('PRD', 'PRODUCT'), ('PRDG', 'PRODUCT-GROUP')])),
                ('resource_id', models.IntegerField(help_text='Id of resource')),
                ('valid_always', models.BooleanField(default=False)),
                ('validity_days', models.IntegerField(default=0, help_text='Number of valid days for subscription')),
                ('cost_price', models.FloatField()),
                ('selling_price', models.FloatField()),
                ('created_by_id', models.IntegerField()),
                ('consumption', models.IntegerField(default=0)),
                ('limited_consumption_valid', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('user_id', models.IntegerField(help_text='User id with a subscription')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('is_end_date_applicable', models.BooleanField(default=False)),
                ('consumption', models.IntegerField(default=0)),
                ('limited_consumption_valid', models.BooleanField(default=False)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_subscriptions', to='gypermission.subscription')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
