# Generated by Django 5.0.1 on 2024-03-04 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyproduct', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('help_email', models.EmailField(blank=True, help_text='An email to support issues in these topics', max_length=254, null=True)),
                ('created_by_id', models.CharField(max_length=10)),
                ('updated_by_id', models.CharField(max_length=10)),
                ('min_age', models.IntegerField(blank=True, null=True)),
                ('custom_parameters', models.JSONField(blank=True, default=dict, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
