# Generated by Django 5.0.1 on 2024-03-04 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyproduct', '0002_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('icon', models.URLField(blank=True, help_text='An image as an icon to the topic', null=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('help_email', models.EmailField(blank=True, help_text='An email to support issues in these topics', max_length=254, null=True)),
                ('created_by_id', models.CharField(max_length=10)),
                ('updated_by_id', models.CharField(max_length=10)),
                ('custom_parameters', models.JSONField(blank=True, default=dict, null=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='topics', to='gyproduct.department')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
