# Generated by Django 5.0.1 on 2024-03-04 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyproduct', '0003_topic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eligibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('parameter', models.CharField(choices=[('Age', 'Age Limit'), ('ACD', 'Academic')])),
                ('lower_limit', models.IntegerField()),
                ('upper_limit', models.IntegerField()),
                ('custom_parameters', models.JSONField(blank=True, default=dict, null=True)),
            ],
            options={
                'unique_together': {('parameter', 'lower_limit', 'upper_limit')},
            },
        ),
    ]
