# Generated by Django 5.0.1 on 2024-03-04 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyproduct', '0005_productgroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.URLField(blank=True, null=True)),
                ('created_by_id', models.CharField(max_length=10)),
                ('updated_by_id', models.CharField(max_length=10)),
                ('cost_price', models.PositiveBigIntegerField()),
                ('selling_price', models.PositiveBigIntegerField()),
                ('owned_by', models.CharField(choices=[('LM', 'Learnmate'), ('CR', 'Customer')], max_length=3)),
                ('approved_by_id', models.CharField(max_length=10)),
                ('limited_consumption', models.BooleanField(default=False, help_text='If publisher wants to limit the consumption')),
                ('consumption_quantity', models.FloatField(default=0.0, help_text='If limited consumption is applicable then there must be consumption quantity')),
                ('is_sellable', models.BooleanField(default=False)),
                ('limited_sale_applicable', models.BooleanField(default=False, help_text='If there are only limited quantity available for sale')),
                ('quantity', models.FloatField(default=0.0, help_text='If limited sale applicable then there must be limited quanity')),
                ('custom_parameters', models.JSONField(blank=True, default=dict, null=True)),
                ('eligibility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product', to='gyproduct.eligibility')),
                ('product_group', models.ForeignKey(help_text='A product group created at time when products are published', on_delete=django.db.models.deletion.PROTECT, related_name='products', to='gyproduct.productgroup')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
