# Generated by Django 5.0.1 on 2024-03-05 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyproduct', '0006_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceContents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('resource_type', models.CharField(choices=[('PRD', 'PRODUCT'), ('PRDG', 'PRODUCT-GROUP')])),
                ('resource_id', models.IntegerField(help_text='Id of resource')),
                ('video_content_link', models.URLField(blank=True, null=True)),
                ('audio_content_link', models.URLField(blank=True, null=True)),
                ('written_content_link', models.URLField(blank=True, null=True)),
                ('image_content_link', models.URLField(blank=True, null=True)),
                ('custom_parameters', models.JSONField(blank=True, default=dict, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
