# Generated by Django 5.0.1 on 2024-03-10 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyproduct', '0007_resourcecontents'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=151)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PublisherCategoryDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_till', models.DateTimeField(blank=True, null=True)),
                ('issued_by', models.CharField()),
                ('is_required', models.BooleanField(default=False)),
                ('category', models.ForeignKey(help_text='Category for which docs is required', on_delete=django.db.models.deletion.CASCADE, related_name='category_documents', to='gyproduct.category')),
                ('documents', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gyproduct.documenttype')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
