# Generated by Django 5.0.1 on 2024-05-30 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyproduct', '0008_documenttype_publishercategorydocuments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productgroup',
            name='icon',
            field=models.URLField(blank=True, help_text='An icon which can be thumbnail', null=True),
        ),
    ]
