# Generated by Django 5.0.1 on 2024-05-30 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyproduct', '0009_alter_productgroup_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='eligibility',
            name='multiplier',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='product',
            name='mrp',
            field=models.FloatField(default=10000000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productgroup',
            name='mrp',
            field=models.FloatField(default=10000000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='created_by_id',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='category',
            name='updated_by_id',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='department',
            name='created_by_id',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='department',
            name='updated_by_id',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='eligibility',
            name='lower_limit',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='eligibility',
            name='upper_limit',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='approved_by_id',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='cost_price',
            field=models.FloatField(),
        ),
        migrations.RemoveField(
            model_name='product',
            name='eligibility',
        ),
        migrations.AlterField(
            model_name='product',
            name='selling_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='productgroup',
            name='approved_by_id',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='productgroup',
            name='cost_price',
            field=models.FloatField(),
        ),
        migrations.RemoveField(
            model_name='productgroup',
            name='eligibility',
        ),
        migrations.AlterField(
            model_name='productgroup',
            name='selling_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='topic',
            name='created_by_id',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='topic',
            name='updated_by_id',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AddField(
            model_name='product',
            name='eligibility',
            field=models.ManyToManyField(related_name='product', to='gyproduct.eligibility'),
        ),
        migrations.AddField(
            model_name='productgroup',
            name='eligibility',
            field=models.ManyToManyField(related_name='product_group', to='gyproduct.eligibility'),
        ),
    ]
