# Generated by Django 5.0.1 on 2024-03-09 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyuser', '0002_alter_profile_is_working'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='block',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.CharField(default=models.EmailField(max_length=254, null=True, verbose_name='Initial Email Address'), max_length=251, unique=True),
        ),
    ]
