# Generated by Django 5.0.1 on 2024-05-30 18:46

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyuser', '0004_user_is_publisher_publisherapproval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='preferred_languages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=5), default=None, help_text='Language codes of preferred languages in preference order', null=True, size=None),
        ),
    ]
