# Generated by Django 5.0.1 on 2024-06-14 20:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyuser', '0007_alter_user_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='current_timezone',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='email_init',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='exams_interested_in',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='friends',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='google_plus',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='timezones',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='username',
        ),
        migrations.AddField(
            model_name='profile',
            name='full_name',
            field=models.CharField(blank=True, help_text='Full name of user', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(help_text='User', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
